[[constraint]]
  name = "github.com/sarulabs/di"
  version = "v2.4.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/stevenroose/gonfig"
  version = "0.1.4"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.1"