[[constraint]]
  name = "github.com/sarulabs/di"
  version = "v2.4.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/stevenroose/gonfig"
  version = "0.1.5"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.9.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.5.1"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "v8.0.6"

[[constraint]]
  name = "github.com/google/go-querystring"
  version = "v1.0.0"