// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/sepuka/campaner/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TaskManager is an autogenerated mock type for the TaskManager type
type TaskManager struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: taskId, userId
func (_m TaskManager) Cancel(taskId int64, userId int) error {
	ret := _m.Called(taskId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int) error); ok {
		r0 = rf(taskId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Copy provides a mock function with given fields: taskId, reminder, minutes
func (_m TaskManager) Copy(taskId int64, reminder *domain.Reminder, minutes int) error {
	ret := _m.Called(taskId, reminder, minutes)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *domain.Reminder, int) error); ok {
		r0 = rf(taskId, reminder, minutes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
